### ISSUE TITLE
Native host has exited.

### ISSUE THREAD

**Issue by Sneaken** [guest271314/native-messaging-nodejs#2]
use your nm_nodejs.js

chrome.runtime.lastError is 'Native host has exited'.

i don't know what happened.. can you help me?

env: m1 mac
node 20
chrome: 126.0.6478.127 arm64

![image](https://github.com/user-attachments/assets/8e92e52e-1a64-4f6e-941f-3b4eb05a9513)
![image](https://github.com/user-attachments/assets/ae6837f8-10a0-4981-a53d-0ebb6fe1cdff)
![image](https://github.com/user-attachments/assets/bbddc2dd-641a-4155-937b-80bfa000377c)

**Comment by guest271314** [comment]
Is `nm_node.js` is set executable?

**Comment by Sneaken** [comment]
> Is `nm_node.js` is set executable?

yes

chmod +x  ./nm_nodejs.js

**Comment by guest271314** [comment]
Make sure  the value of `"path"` in `nm_nodejs.json` is pointing to the absolute path to the file on the file system. Also try with each of the following flags on shebag line removed  `--max-old-space-size=14 --jitless --expose-gc --v8-pool-size=1`.

**Comment by guest271314** [comment]
Excluding `--expose-gc`, which doesn't change anything with regard to `node` exiting, while the others can.

**Comment by guest271314** [comment]
Did you update the shebang line in `nm_nodejs.js` to point to the absolute path to the `node` executable you are using?

```
#!/usr/bin/env -S /home/user/bin/node  --expose-gc  --experimental-default-type=module
```

**Comment by Sneaken** [comment]
> Did you update the shebang line in `nm_nodejs.js` to point to the absolute path to the `node` executable you are using?
> 
> ```
> #!/usr/bin/env -S /home/user/bin/node  --expose-gc  --experimental-default-type=module
> ```

yes , but no change

```
#!/usr/bin/env -S /Users/sneaken/.volta/bin/node --expose-gc --experimental-default-type=module
```

**Comment by guest271314** [comment]
The only other report I have gotten was from another Mac user. I'm running the same code you are running on Linux, Chromium 128.

![Screenshot_2024-07-15_00-35-23](https://github.com/user-attachments/assets/bae8bd57-0a27-4c5e-ae0b-3c3fc02dc4cb)


What happens when you try Deno, Bun, and shell script as Native Messaging hosts?

**Comment by Sneaken** [comment]
I tried the official Python code, and it works. This is strange because only Node.js doesn’t work on my computer.

**Comment by guest271314** [comment]
Here are a few Native Messaging hosts that should all send back the same result, an `Array` with `length` `209715`, `1048576` bytes as JSON https://github.com/guest271314/NativeMessagingHosts.

It's probably something like paths not being absolute or files not being executable. 

I would reload the extension. Go over the code until you locate the issue. Is `node` executable?

**Comment by guest271314** [comment]
This script should work using `node`, `deno`, or `bun` https://github.com/guest271314/NativeMessagingHosts/blob/main/nm_host.js. What happens when you substitute adjust `"path"` in `nm_nodejs.json` to `nm_host.js`, adjust shebang line, make the script executable and run the code?

**Comment by Sneaken** [comment]
> Here are a few Native Messaging hosts that should all send back the same result, an `Array` with `length` `209715`, `1048576` bytes as JSON https://github.com/guest271314/NativeMessagingHosts.
> 
> It's probably something like paths not being absolute or files not being executable.
> 
> I would reload the extension. Go over the code until you locate the issue. Is `node` executable?

Error when communicating with the native messaging host.

![image](https://github.com/user-attachments/assets/c52f5cfa-bf5d-4d76-a8ee-b35a5549677b)
![image](https://github.com/user-attachments/assets/a3843a5d-667a-4afe-bbff-27b3c34f40d5)

**Comment by Sneaken** [comment]
> Here are a few Native Messaging hosts that should all send back the same result, an `Array` with `length` `209715`, `1048576` bytes as JSON https://github.com/guest271314/NativeMessagingHosts.
> 
> It's probably something like paths not being absolute or files not being executable.
> 
> I would reload the extension. Go over the code until you locate the issue. Is `node` executable?

python can run... my God

**Comment by guest271314** [comment]
Sounds like a path or executable permission issue.

**Comment by guest271314** [comment]
In the last image you posted you are pointing to `node` on the shebang. In the other image you pointed to `/Users/sneaken/.volta/bin/node`.

Make sure you are pointing to the absolute pathe to `node` if `node` is not installed system wide.

**Comment by Sneaken** [comment]
> Sounds like a path or executable permission issue.

sorry, nm_host.js need node 21, when i install it, it can run!!

**Comment by guest271314** [comment]
In theory `nm_nodejs.js` should run, too. I'm not sure if pointing to the file descriptors `/dev/stdin` and `/proc/self/fd/1` is an issue on Mac.

**Comment by Sneaken** [comment]
> Here are a few Native Messaging hosts that should all send back the same result, an `Array` with `length` `209715`, `1048576` bytes as JSON https://github.com/guest271314/NativeMessagingHosts.
> 
> It's probably something like paths not being absolute or files not being executable.
> 
> I would reload the extension. Go over the code until you locate the issue. Is `node` executable?

but nm_nodejs.js still like that... MY GOD

**Comment by Sneaken** [comment]
> In theory `nm_nodejs.js` should run, too. I'm not sure if pointing to the file descriptors `/dev/stdin` and `/proc/self/fd/1` is an issue on Mac.

I feel like this might be the problem

**Comment by Sneaken** [comment]
Although I don’t know what happened, thank you for answering my questions.  :)

**Comment by guest271314** [comment]
I don't generally use Apple devices. Thanks for the feedback re Mac and `nm_nodejs.js`. 

`nm_node.js.js` works for me on Linux, with `node` and Chromium from tip-of-tree releases fetched today.

I wrote `nm_host.js` as a JavaScript runtime agnostic approach to reading standard input and writing to standard output, primarily using WHATWG Streams that is not part of ECMA-262 though works reliably for streaming `Uint8Array`s and resizable `ArrayBuffer`, with `dataView` to read "32-bit message length in native byte order.". Unfortunately, reading standard input and writing to standard output is not standardized in ECMA-262, so it's continual W.I.P. to use the same code across engines and runtimes, e.g., `Bun.stdin.stream()` does not beahve the same as `Bun.file("/dev/stdin").stream()`.

What happens when you try this code https://github.com/simov/native-messaging/blob/8e99d2a345ae94426a502d05aa5d57b966f6bc78/protocol.js and this code https://github.com/guest271314/NativeMessagingHosts/blob/5306ae8a09f6dd1e8053e737ad244ffd7ca2ecb3/nm_nodejs.mjs?

**Comment by guest271314** [comment]
> Although I don’t know what happened, thank you for answering my questions. :)

No worries.

**Comment by Sneaken** [comment]
use `https://github.com/guest271314/NativeMessagingHosts/blob/5306ae8a09f6dd1e8053e737ad244ffd7ca2ecb3/nm_nodejs.mjs`

emmm... haha

![image](https://github.com/user-attachments/assets/78f1c5ef-46b1-482d-aae5-d96cc92c71f8)

**Comment by guest271314** [comment]
Did you remove `--max-old-space-size=6`,  `--jitless`, and  `--v8-pool-size=1` flags from shebang line?

And if that doesn't change anything, removing `process.env.UV_THREADPOOL_SIZE = 1;`
 and `process.stdout._handle.setBlocking(true);`?

**Comment by Sneaken** [comment]
this can work `https://github.com/simov/native-messaging/blob/8e99d2a345ae94426a502d05aa5d57b966f6bc78/protocol.js`

**Comment by Sneaken** [comment]
> Did you remove `--max-old-space-size=6`, `--jitless`, and `--v8-pool-size=1` flags from shebang line?
> 
> And if that doesn't change anything, removing `process.env.UV_THREADPOOL_SIZE = 1;` and `process.stdout._handle.setBlocking(true);`?

this all no change, maybe should use stream on mac

**Comment by Sneaken** [comment]
Thank you once again 😆
